<a href="https://colab.research.google.com/github/anumit-web/Numpy-tutorial-2/blob/main/Numpy_test_2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy functions


create array

In [26]:
# np create function

In [27]:
arr = np.zeros(5)
print(arr)  # [0. 0. 0. 0. 0.]

print("--------------------")

# Create a 2D array with 3 rows and 4 columns, filled with zeros
arr = np.zeros((3, 4))
print(arr)
# [[0. 0. 0. 0.]
#  [0. 0. 0. 0.]
#  [0. 0. 0. 0.]]


[0. 0. 0. 0. 0.]
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:

# Create a 1D array with 5 ones
arr = np.ones(5)
print(arr)  # [1. 1. 1. 1. 1.]

print("--------------------")

# Create a 2D array with 3 rows and 4 columns, filled with ones
arr = np.ones((3, 4))
print(arr)
# [[1. 1. 1. 1.]
#  [1. 1. 1. 1.]
#  [1. 1. 1. 1.]]

[1. 1. 1. 1. 1.]
--------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [29]:

# Create an empty 1D array with 5 elements
arr = np.empty(5)
print(arr)  # [ random values ]

print("--------------------")

# Create an empty 2D array with 3 rows and 4 columns
arr = np.empty((3, 4))
print(arr)
# [[ random values ]
#  [ random values ]
#  [ random values ]]

[1. 1. 1. 1. 1.]
--------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
