<a href="https://colab.research.google.com/github/anumit-web/Numpy-tutorial-2/blob/main/Numpy_test_2_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

https://www.programiz.com/python-programming/numpy/introduction

In [25]:
import numpy as np

In [26]:
import numpy as np

# create a list named list1
list1 = [2, 4, 6, 8]

# create numpy array using list1
array1 = np.array(list1)

print(array1)

# Output: [2 4 6 8]

[2 4 6 8]


In [27]:
import numpy as np

# create numpy array using a list
array1 = np.array([2, 4, 6, 8])
print(array1)

# Output: [2  4  6 8]

[2 4 6 8]


Create an Array Using np.zeros()

In [28]:
import numpy as np

# create an array with 4 elements filled with zeros
array1 = np.zeros(4)

print(array1)

# Output: [0. 0. 0. 0.]

[0. 0. 0. 0.]


In [29]:
import numpy as np

# create an array with values from 0 to 4
array1 = np.arange(5)

print("Using np.arange(5):", array1)

# create an array with values from 1 to 8 with a step of 2
array2 = np.arange(1, 9, 2)

print("Using np.arange(1, 9, 2):",array2)

Using np.arange(5): [0 1 2 3 4]
Using np.arange(1, 9, 2): [1 3 5 7]


In [30]:
import numpy as np

# generate an array of 5 random numbers
array1 = np.random.rand(5)

print(array1)

[0.27015747 0.38735075 0.44094588 0.38170677 0.1586819 ]


In [31]:
import numpy as np

# create an empty array of length 4
array1 = np.empty(4)

print(array1)

[4.9e-324 1.5e-323 2.5e-323 3.5e-323]
