<a href="https://colab.research.google.com/github/anumit-web/Numpy-tutorial-2/blob/main/Numpy_test_2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy functions


create array

In [ ]:
# np create function

In [ ]:
arr = np.zeros(5)
print(arr)  # [0. 0. 0. 0. 0.]

# Create a 2D array with 3 rows and 4 columns, filled with zeros
arr = np.zeros((3, 4))
print(arr)
# [[0. 0. 0. 0.]
#  [0. 0. 0. 0.]
#  [0. 0. 0. 0.]]
