<a href="https://colab.research.google.com/github/anumit-web/Numpy-tutorial-2/blob/main/Numpy_test_2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy functions


create array

In [36]:
# np create function

In [37]:
arr = np.zeros(5)
print(arr)  # [0. 0. 0. 0. 0.]

print("--------------------")

# Create a 2D array with 3 rows and 4 columns, filled with zeros
arr = np.zeros((3, 4))
print(arr)
# [[0. 0. 0. 0.]
#  [0. 0. 0. 0.]
#  [0. 0. 0. 0.]]


[0. 0. 0. 0. 0.]
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [38]:

# Create a 1D array with 5 ones
arr = np.ones(5)
print(arr)  # [1. 1. 1. 1. 1.]

print("--------------------")

# Create a 2D array with 3 rows and 4 columns, filled with ones
arr = np.ones((3, 4))
print(arr)
# [[1. 1. 1. 1.]
#  [1. 1. 1. 1.]
#  [1. 1. 1. 1.]]

[1. 1. 1. 1. 1.]
--------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [39]:

# Create an empty 1D array with 5 elements
arr = np.empty(5)
print(arr)  # [ random values ]

print("--------------------")

# Create an empty 2D array with 3 rows and 4 columns
arr = np.empty((3, 4))
print(arr)
# [[ random values ]
#  [ random values ]
#  [ random values ]]

[1. 1. 1. 1. 1.]
--------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [40]:
# numpy.arange(start, stop, step, dtype=None)

In [41]:
# Create an array with values from 0 to 9
arr = np.arange(10)
print(arr)  # [0 1 2 3 4 5 6 7 8 9]

# Create an array with values from 1 to 10
arr = np.arange(1, 11)
print(arr)  # [1 2 3 4 5 6 7 8 9 10]

# Create an array with values from 0 to 10 with a step of 2
arr = np.arange(0, 11, 2)
print(arr)  # [0 2 4 6 8 10]

# Create an array with values from 10 to 0 with a step of -1
arr = np.arange(10, -1, -1)
print(arr)  # [10 9 8 7 6 5 4 3 2 1 0]

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]
[10  9  8  7  6  5  4  3  2  1  0]
